### ISSUE TITLE
Slack integration to display items + expose add-item action

### ISSUE THREAD

**Issue by Daenyth** [nbashaw/updwn-slack#3]
I think this would make it quite useful. Keeping people in slack keeps it more discoverable for a larger team. How hard would this be to add?

**Comment by nbashaw** [comment]
Totally! Honestly this is a somewhat defunct project. For a much better slack integration, check out https://simplepoll.rocks/

**Comment by Daenyth** [comment]
That's unfortunate. Simplepoll really doesn't do the same thing at all
